name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build:vite
      - run: npx electron-builder --linux --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: Linux-AppImage
          path: release/*.AppImage

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build:vite
      - run: npx electron-builder --mac --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: macOS-安装包
          path: release/*.dmg

  win-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build:vite
      - run: npx electron-builder --win --x64 --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-x64-安装版
          path: release/* Setup *.exe

  win-x64-portable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build:vite
      - run: npx electron-builder --win --x64 --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-x64-便携版
          path: release/*.zip

  win-ia32:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build:vite
      - run: npx electron-builder --win --ia32 --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-32位-安装版
          path: release/* Setup *.exe

  win-arm64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build:vite
      - run: npx electron-builder --win --arm64 --publish=never
      - uses: actions/upload-artifact@v4
        with:
          name: Windows-ARM-安装版
          path: release/* Setup *.exe
